### ISSUE TITLE
Refactor changeWalkerSchedule and addWalkerSchedule 

### ISSUE THREAD

**Issue by preyansh98** [preyansh98/safeHome#19]
Encapsulate parameters in a class

**Comment by preyansh98** [comment]
change signature to take (int mcgillID, ScheduleDTO)

**Comment by HimanshuRanka** [comment]
I can do this one

**Comment by Oussama99-OM** [comment]
i'm doing it with you,

**Comment by HimanshuRanka** [comment]
TODO: Maybe add a validator within the schedule object itself so we are sure that every schedule being used is valid and don't need to validate it everywhere.

**Comment by preyansh98** [comment]
Resolved
